=== Gracetexana/Non-RelationalDataManagement/Week 2/XMLPe01/LongToralesMenu.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT menu (item+)>
<!ELEMENT item (name, price)>
<!ATTLIST item 
    id CDATA #REQUIRED>
<!ELEMENT  name (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== Gracetexana/Non-RelationalDataManagement/Week 2/LongToralesMenu.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE menu SYSTEM "LongToralesMenu.dtd">
<?xml-stylesheet type="text/xsl" href="LongToralesMenu.xslt"?>
<menu>
    <item id="1">
        <name>Hamburger</name>
        <price>8.75</price>
    </item>
    <item id="2">
        <name>Hot Dog</name>
        <price>6.50</price>
    </item>
    <item id="3">
        <name>Cola Drink</name>
        <price>3.25</price>
    </item>
</menu>
